# Generated by Django 5.2 on 2025-04-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sport/images/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='sport/audio/')),
                ('video', models.FileField(blank=True, null=True, upload_to='sport/video/')),
                ('description', models.TextField()),
            ],
        ),
    ]
