# Generated by Django 5.2 on 2025-04-05 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sports',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 5, 7, 37, 17, 646832, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
